export const actionTypes = {
    APP_TOGGLE: "APP/TOGGLE",
    HOME_PAGE_LOADED: "HOME_PAGE/LOADED",
    // 3 parts
    SAGATEST_REQUEST: "SAGATEST/REQUEST",
    SAGATEST_REQUEST_SUCCEEDED: "SAGATEST/REQUEST_SUCCEEDED",
    SAGATEST_REQUEST_FAILED: "SAGATEST/REQUEST_FAILED",
}